version: "3"

services:
  redis_service:
    image: redis
    container_name: react_redis_cache_container
    expose:
      - 6379

  backend_nodejs_service:
    build: ./backend-node
    container_name: backend_nodejs_container
    depends_on:
      - redis_service
#    ports:
#      - 8001:8001
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://react_redis_cache_container
      - PORT=8001
    ports:
      - 8001:8001
    command: npm run start

  backend_corecs_service:
    build: ./backend-core
    container_name: backend_corecs_container
    depends_on:
      - redis_service
#    ports:
#      - 8002:80
    ports:
      - 8002:8002
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://react_redis_cache_container      
      - PORT=8002

# https://github.com/mrcoles/node-react-docker-compose/blob/master/docker-compose.yml
  frontend_react_service:
    image: frontend-react
    container_name: frontend_react_container
    build: ./frontend-react
    depends_on:
      - backend_nodejs_service
      - backend_corecs_service
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_DOMAIN_BACKEND_NODEJS=backend_nodejs_service
      - REACT_APP_DOMAIN_BACKEND_CORECS=backend_corecs_service
      - REACT_APP_PORT_BACKEND_NODEJS=8001
      - REACT_APP_PORT_BACKEND_CORECS=8002
#      - REACT_APP_SOME_ENV_VARIABLE_1=abc123
    command: npm run start

# https://mherman.org/blog/dockerizing-an-angular-app/
  frontend_angular_service:
    image: frontend-angular
    container_name: frontend_angular_container
    build: ./frontend-angular
    depends_on:
      - backend_nodejs_service
      - backend_corecs_service
#    volumes:
#      - '.:/usr/src/app'
#      - '/usr/src/app/node_modules'
    ports:
      - 4200:4200
    environment:
      - NODE_ENV=development
      - DOMAIN_BACKEND_NODEJS=backend_nodejs_service
      - DOMAIN_BACKEND_CORECS=backend_corecs_service
      - PORT_BACKEND_NODEJS=8001
      - PORT_BACKEND_CORECS=8002