version: "3"

services:
  redis_service:
    image: redis
    container_name: react_redis_cache_container
    expose:
      - 6379

  backend_nodejs_service:
    build: ./backend-node
    container_name: backend_nodejs_container
    depends_on:
      - redis_service
    ports:
      - 8001:8001
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://react_redis_cache_container
      - PORT=8001
    command: npm run start

  backend_corecs_service:
    build: ./backend-core
    container_name: backend_corecs_container
    depends_on:
      - redis_service
    ports:
      - 8002:80
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://react_redis_cache_container      

# https://github.com/mrcoles/node-react-docker-compose/blob/master/docker-compose.yml
  frontend_react_service:
    image: frontend-react
    container_name: frontend_react_container
    build: ./frontend-react
    depends_on:
      - backend_nodejs_service
      - backend_corecs_service
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
#      - REACT_APP_SOME_ENV_VARIABLE_1=abc123
    command: npm run start

