version: "3"

services:
  redis_service:
    image: redis
    container_name: react_redis_cache
    expose:
      - 6379

  backend_nodejs_service:
    build: ./backend-node
    container_name: backend_nodejs
    volumes:
      - ../redis-react-back/:/var/www/app
    links:
      - redis_service
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://react_redis_cache
      - PORT=3001
    command:
      sh -c 'npm install && node server.js'

  backend_corecs_service:
    build: ./backend-core
    container_name: backend_corecs
    volumes:
      - ../redis-core-back/:/var/www/app
    links:
      - redis_service
    ports:
      - 3002:80
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://react_redis_cache
      - PORT=3002

# https://github.com/mrcoles/node-react-docker-compose/blob/master/docker-compose.yml
  frontend_react:
    image: frontend-react
    container_name: frontend-react
    build: ./frontend-react
    links:
      - backend_nodejs_service
      - backend_corecs_service
    ports:
      - 3000:3000
    volumes:
      - ./frontend-react:/app
    environment:
      - REACT_APP_BACKEND_URL_NODEJS=http://192.168.1.19:3001
      - REACT_APP_BACKEND_URL_CORECS=http://192.168.1.19:3002
      - NODE_ENV=development
      - PORT=3000
    command:
      npm start
